### ISSUE TITLE
Make output dir configurable

### ISSUE THREAD

**Issue by tbeseda** [enhance-dev/arc-plugin-rollup#4]
Given a config in `.arc`, the output directory name (in public/) should be configurable.

What should the pragma name be? the config key name?

```bash
@app
my-enhance-app

@plugins
enhance/arc-plugin-enhance

# @bundles is taken

@browser-js # maybe?
outputDir bundles # would output to <project-root>/public/bundles
```

**Comment by clintjhill** [comment]
Is it possible that #5 allows for this to be unnecessary?

With the solution in #5 Enhance project config doesn't necessarily have to proxy this config for Rollup. Instead it's left to the owner and their own `rollup.config.js` to manage changes to output.

This should leave Enhance with the singular `browser` to `public` plumbing for these files, but allow the owner to extend that flow with configs from Rollup.

**Comment by kristoferjoseph** [comment]
No longer needed due to the ability to use your own config thanks to @clintjhill 🤗
